### PR TITLE
Switch to C++17

### LINKED ISSUE #568: Switch to C++17
Needed for #550

### LINKED ISSUE #569: warnings building DPDK with C++17
The dpdk library is using the `register` keyword that got removed in C++17. 

```
[ 18%] Building CXX object lib/dpdk/CMakeFiles/kotekan_dpdk.dir/dpdkCore.cpp.o

In file included from /opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_ether.h:53:0,

                 from /opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:185,

                 from /data/jenkins/kotekan_rn_c_17/lib/dpdk/dpdkCore.hpp:20,

                 from /data/jenkins/kotekan_rn_c_17/lib/dpdk/dpdkCore.cpp:1:

/opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_byteorder.h: In function ‘uint16_t rte_arch_bswap16(uint16_t)’:

/opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:56:20: error: ISO C++1z does not allow ‘register’ storage class specifier [-Werror=register]

  register uint16_t x = _x;

                    ^

/opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_byteorder.h: In function ‘uint32_t rte_arch_bswap32(uint32_t)’:

/opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:71:20: error: ISO C++1z does not allow ‘register’ storage class specifier [-Werror=register]

  register uint32_t x = _x;

                    ^

In file included from /opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_byteorder.h:120:0,

                 from /opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_ether.h:53,

                 from /opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:185,

                 from /data/jenkins/kotekan_rn_c_17/lib/dpdk/dpdkCore.hpp:20,

                 from /data/jenkins/kotekan_rn_c_17/lib/dpdk/dpdkCore.cpp:1:

/opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_byteorder_64.h: In function ‘uint64_t rte_arch_bswap64(uint64_t)’:

/opt/dpdk-stable-16.11.4/x86_64-native-linuxapp-gcc/include/rte_byteorder_64.h:52:20: error: ISO C++1z does not allow ‘register’ storage class specifier [-Werror=register]

  register uint64_t x = _x;

                    ^

```

Needed for #568

### PR DESCRIPTION
**Pull request by nritsche**
<s>Can someone try building this with clang, please?</s>

This doesn't compile with gcc-5.

Closes #569
Closes #568

### CODE REVIEW

**Comment by nritsche** [comment]
Builds fine with `clang-10/8/3.8` on Ubuntu.
@andrerenard Please merge if you approve.

**Comment by jrs65** [comment]
👍
